### ISSUE TITLE
BLYNK_WRITE(Vx) not firing when using write node

### ISSUE THREAD

**Issue by chinswain** [gablau/node-red-contrib-blynk-ws#1]
I've just noticed that when triggering the write node it updates the mobile app element but not the hardware side, if I Blynk.syncVirtual(Vx) it sync's the status - is it possible to update both hardware and app without sync? 

As per the RESTful API: http://blynk-cloud.com/<TOKEN>/update/V4?value=1

**Comment by gablau** [comment]
Hi chinswain,
at the moment there is no node implementing the hw_sync call.
Certainly it could be one thing to implement in the future.

I did not understand if it is to be implemented in the write node or if it is implemented with another node.
If you have any information on how to implement it or if you have any other requests let me know.

Greetings

**Comment by gablau** [comment]
With version 0.5.0 I implemented the "syncAll" and "syncVirtual" commands in the Sync node
