### ISSUE TITLE
Vpin settings not remembered first time around

### ISSUE THREAD

**Issue by Peterkn2001** [gablau/node-red-contrib-blynk-ws#12]
I'm using v0.9.1, but not sure if this existed in earlier versions.

If you drag a new Blynk node onto a flow, double-click and set the virtual pin number then click 'Done', the virtual pin always reverts to '0'.
Double-clicking and editing the node to the required Vpin number and clicking 'Done` updates the node to the correct setting.

Virtual Pin set to 4:

![image](https://user-images.githubusercontent.com/35718564/56474827-4ef3d800-6477-11e9-9a5e-83c0d26ab7f0.png)

but it reverts to 0 when you click 'Done':
![image](https://user-images.githubusercontent.com/35718564/56474834-76e33b80-6477-11e9-9318-e912b6ed4037.png)

Editing and changing back to 4 again solves the problem:
![image](https://user-images.githubusercontent.com/35718564/56474855-c45fa880-6477-11e9-8f63-376372bb9b20.png)

Pete.

**Comment by gablau** [comment]
Hi Pete,
thanks for reporting, i corrected the problem.
The fix will be published in the next release.

**Comment by Peterkn2001** [comment]
Thanks!
