### ISSUE TITLE
Unable to connect to Blynk server across the internet...

### ISSUE THREAD

**Issue by aaro668** [gablau/node-red-contrib-blynk-ws#14]
Hi,
I am having trouble connecting to my own blynk server across the internet.
I have RPi running local blynk server on my own network at home (internal IP adress is 192.168.0.59), here is the server.properties file:
[server.zip](https://github.com/gablau/node-red-contrib-blynk-ws/files/3673341/server.zip)
I have node-red running on a RPi that is not on my local network, but it needs to access the local blynk server across the internet and through port forwarding.
In node-red I have blynk ws node set up like this:
![image](https://user-images.githubusercontent.com/34253498/65915347-4944db80-e3a1-11e9-9987-dc30d07ced02.png)
(I have scribbled the public IP address for security)
On my main router I have port forwarding set up like this: incoming port 9494 > local IP 192.168.0.59 local Port 8080
I would have expected this to work, but instead I am getting these errors:
![image](https://user-images.githubusercontent.com/34253498/65915768-1818db00-e3a2-11e9-8d4f-38195236849b.png)

And I am unable to get it to connect.
 Am I missing something here? I did read that I might need a certificate, how do I set this up to work?
thanks!

**Comment by gablau** [comment]
Hi,
I don't know if you have already solved the problem, to me it would seem to be a problem of internet connectivity.

let me know
Regards
