### ISSUE TITLE
After changing the router the nodered flows with node-red-contrib-blynk-ws does not work.

### ISSUE THREAD

**Issue by gurues** [gablau/node-red-contrib-blynk-ws#16]
Hello

After changing the router the nodered flows with node-red-contrib-blynk-ws does not work.

Error log nodered:

starting as a systemd service.
10 Oct 15:19:42 - [info] [blynk-ws-client:Blynk-gurues] Start secure connection: wss://blynk-cloud.com/websockets
10 Oct 15:19:57 - [error] [blynk-ws-client:Blynk-Control Home] Websocket Error: getaddrinfo EAI_AGAIN blynk-cloud.com blynk-cloud.com:443
10 Oct 15:19:57 - [info] [blynk-ws-client:Blynk-Control Home] Client Error
10 Oct 15:19:57 - [info] [blynk-ws-client:Blynk-Control Home] Reconnect in 5 seconds...
10 Oct 15:19:57 - [info] [blynk-ws-client:Blynk-Control Home] Websocket closed: wss://blynk-cloud.com/websockets
10 Oct 15:19:57 - [info] [blynk-ws-client:Blynk-Control Home] Reconnect in 5 seconds...
10 Oct 15:19:58 - [error] [openweathermap:Tiempo Cambrils] Error: getaddrinfo EAI_AGAIN api.openweathermap.org api.openweathermap.org:80
10 Oct 15:20:02 - [info] [blynk-ws-client:Blynk-Control Home] Start secure connection: wss://blynk-cloud.com/websockets
10 Oct 15:20:18 - [error] [blynk-ws-client:BLINK-ALARMA] Websocket Error: getaddrinfo EAI_AGAIN blynk-cloud.com blynk-cloud.com:443
10 Oct 15:20:18 - [info] [blynk-ws-client:BLINK-ALARMA] Client Error
10 Oct 15:20:18 - [info] [blynk-ws-client:BLINK-ALARMA] Reconnect in 5 seconds...
10 Oct 15:20:18 - [info] [blynk-ws-client:BLINK-ALARMA] Websocket closed: wss://blynk-cloud.com/websockets
10 Oct 15:20:18 - [info] [blynk-ws-client:BLINK-ALARMA] Reconnect in 5 seconds...
10 Oct 15:20:23 - [info] [blynk-ws-client:BLINK-ALARMA] Start secure connection: wss://blynk-cloud.com/websockets

Help me please, 
I can't find a solution

**Comment by Peterkn2001** [comment]
Is your new router on the same IP address as your old one?
My guess is that your RPi (or whatever you’re running Node-Red on) can’t see the internet. If you previously set the device up with a static IP, as opposed to one assigned by DHCP, then you’ll need to update your networking settings so that it knows how to find the router.
Easiest way to check if you have internet connectivity is to try pinging google.com from your device.
Pete.

**Comment by gurues** [comment]
> Is your new router on the same IP address as your old one?
> My guess is that your RPi (or whatever you’re running Node-Red on) can’t see the internet. If you previously set the device up with a static IP, as opposed to one assigned by DHCP, then you’ll need to update your networking settings so that it knows how to find the router.
> Easiest way to check if you have internet connectivity is to try pinging google.com from your device.
> Pete.

Thanks Pete

Me RPi have this configuration of red:

pi@raspberrypi:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.100  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::e8aa:b0d:b02b:6480  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:99:55:26  txqueuelen 1000  (Ethernet)
        RX packets 3468  bytes 352815 (344.5 KiB)
        RX errors 0  dropped 7  overruns 0  frame 0
        TX packets 10118  bytes 1541939 (1.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 543  bytes 70246 (68.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 543  bytes 70246 (68.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.99  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::808:6a9a:92d6:4350  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:cc:00:73  txqueuelen 1000  (Ethernet)
        RX packets 2614  bytes 940399 (918.3 KiB)
        RX errors 0  dropped 15  overruns 0  frame 0
        TX packets 41  bytes 4846 (4.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Don't connect to internet, with the browser and "www.google.com " ( not run ) but
ping 216.58.215.46
PING 216.58.215.46 (216.58.215.46) 56(84) bytes of data.
64 bytes from 216.58.215.46: icmp_seq=1 ttl=52 time=33.7 ms
64 bytes from 216.58.215.46: icmp_seq=2 ttl=52 time=33.5 ms
64 bytes from 216.58.215.46: icmp_seq=3 ttl=52 time=33.4 ms
64 bytes from 216.58.215.46: icmp_seq=4 ttl=52 time=33.7 ms
64 bytes from 216.58.215.46: icmp_seq=5 ttl=52 time=33.6 ms
64 bytes from 216.58.215.46: icmp_seq=6 ttl=52 time=33.4 ms
^C
--- 216.58.215.46 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5003ms
rtt min/avg/max/mdev = 33.455/33.614/33.772/0.191 ms

ping is OK.

Help me please I don't undertand

**Comment by gurues** [comment]
pi@raspberrypi:~ $ ping google.com -c 4
ping: google.com: Fallo temporal en la resolución del nombre

pi@raspberrypi:~ $ ping 8.8.8.8 -c 4
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=54 time=22.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=54 time=21.7 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=54 time=19.0 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=54 time=18.2 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 18.202/20.254/22.101/1.677 ms

**Comment by Peterkn2001** [comment]
Looks like you might have a DNS issue.
It’s clearly not an issue with Node-Red or the blynk-ws contrib, but a networking problem.

Pete.

**Comment by gurues** [comment]
Thanks Pete

SOLVED: I change /etc/dhcpcd.conf file en RPi:
static domain_name_servers=192.168.1.1 
static domain_name_servers=8.8.8.8 8.8.8.4

Best Regards
