### ISSUE TITLE
Writing to terminal widget input line possible?

### ISSUE THREAD

**Issue by 877dev** [gablau/node-red-contrib-blynk-ws#17]
HI,

I am using node red of course, and want to send commands to the terminal input line via a node.
At the moment all my strings are appearing in the top box.

Is that possible?

Or maybe via webhooks?

Thanks

**Comment by gablau** [comment]
If I understand correctly, you want to write in the input field of the terminal widget.

I don't think this is possible, in the [official documentation](https://docs.blynk.cc/#widgets-displays-terminal) there is no trace of it

Regards

**Comment by 877dev** [comment]
Hi @gablau 

Yes that's correct. I couldn't see it anywhere in the documentation either.

I guess I will need to send direct from node red to the Arduino code, probably via MQTT.  I've never send data back to the Arduino, normally it's Arduino>node red.

Thanks
