### ISSUE TITLE
Terminal widget

### ISSUE THREAD

**Issue by clementchik0308** [gablau/node-red-contrib-blynk-ws#18]
Hi, Is there any way to clear the terminal widget?

**Comment by 877dev** [comment]
Have you tried sending “clr“ to the terminal Vpin?

**Comment by clementchik0308** [comment]
Problem solved, case closed. Thanks!

**Comment by 877dev** [comment]
@clementchik0308 did you find a solution?

**Comment by clementchik0308** [comment]
> @clementchik0308 did you find a solution?

Yes, send clr to terminal.

**Comment by 877dev** [comment]
My bad, I misunderstood your question. 

Yes there are a couple of ways I know, terminal.clear or Blynk.write(V1, “clr”)

**Comment by clementchik0308** [comment]
> My bad, I misunderstood your question.
> 
> Yes there are a couple of ways I know, terminal.clear if you have the terminal widget defined or Blynk.virtualWrite(V1, “clr”) works either way.

Thx
