### ISSUE TITLE
change of URL in node-config is only picked up after reboot of node-red instance

### ISSUE THREAD

**Issue by VanillaFord** [gablau/node-red-contrib-blynk-ws#29]
...just had an issue with the WS-API (see: https://github.com/blynkkk/blynk-server/issues/1390)
Apparently the URL had changed from ws://........./websockets to ws://........./websocket (no trailing "s").

However, when trying that change of the URL, I noticed that this config change - although running a full deploy of all flows in NR - would only pick up after a restart of the NR instance (using the official NR Docker from Docker Hub, nodered/node-red:latest).

**Comment by gablau** [comment]
Hi, you are right.
Thanks, I'll fix it at the next release.

Greetings

**Comment by gablau** [comment]
Fixed in [1.0.6 version](https://github.com/gablau/node-red-contrib-blynk-ws/releases/tag/1.0.6)
