### ISSUE TITLE
Invalid HW cmd

### ISSUE THREAD

**Issue by mybigman** [gablau/node-red-contrib-blynk-ws#3]
Hi,

First great plugin... have just started playing with it and so far so good.

This error message gets logged to debug. App still functions though.

"Invalid HW cmd: Cmd: HW, Id: 1, len: 2, data: "pm""

Thanks

**Comment by gablau** [comment]
Hi,
it's an error that you can safely ignore!

The hardware command 'pm', is used to set the pin mode. This is important when using pins with boards like arduino, but on nodered is not needed, and is not implemented in the code.
