### ISSUE TITLE
Wrong constant MsgStatus.BLYNK_INVALID_TOKEN is used

### ISSUE THREAD

**Issue by gh-scndml** [gablau/node-red-contrib-blynk-ws#30]
https://github.com/gablau/node-red-contrib-blynk-ws/blob/8022ac8582d5835adbbbc5ba14735926400af72a/libs/blynk-lib.js#L196

I would assume here MsgStatus.BLYNK_INVALID_TOKEN should be MsgStatus.INVALID_TOKEN (as defined in blynk-enum.js).

Best regards
gh

**Comment by gablau** [comment]
Yes, thanks.
I'll fix it on next release.

Greetings

**Comment by gablau** [comment]
Fixed in [1.0.6 version](https://github.com/gablau/node-red-contrib-blynk-ws/releases/tag/1.0.6)
