### ISSUE TITLE
Always get responseCode: CONNECT_REDIRECT

### ISSUE THREAD

**Issue by vossilius** [gablau/node-red-contrib-blynk-ws#5]
Hi,

No matter what I do, the nodes do not connect. Log says:

```
0|node-red | 8 Mar 21:02:48 - [info] [blynk-ws-client:baa3d4b4.f6afb8] login -> 6de884c15e17405589a484b7b064xxxx
0|node-red | 8 Mar 21:02:48 - [info] [blynk-ws-client:baa3d4b4.f6afb8] SEND -> Cmd: LOGIN Id: 1 Data: "\u0002\u0000\u0001\u0000 6de884c15e17405589a484b7b064xxxx"
0|node-red | 8 Mar 21:02:48 - [info] [blynk-ws-client:baa3d4b4.f6afb8] RECV <- Cmd: CONNECT_REDIRECT, Id: 1, responseCode: SERVER_EXCEPTION
0|node-red | 8 Mar 21:03:03 - [info] [blynk-ws-client:baa3d4b4.f6afb8] Connection closed: ws://blynk-cloud.com:8080/websockets
```

Port 8080 is forwarded and I can ping `blynk-cloud.com`.

Also tried to renew the Token but the problem persists.

Any ideas?

Thanks!!
Thomas

**Comment by gablau** [comment]
Hi Thomas,
the cloud server port has changed recently try this: `ws://blynk-cloud.com/websockets` or SSL `wss://blynk-cloud.com/websockets`  or maybe a network problem see [this](https://community.blynk.cc/t/correct-websocket-address-for-blynk-server/22496/19).

You can try your token here `http://blynk-cloud.com/<replace with you token>/project` if return a json your token is OK.

I would be interested to know what version of the library you have, also I would need the versions of nodered and nodejs. Could you post the nodered boot log ??
This is mine:

> 8 Mar 21:27:08 - [info] Node-RED version: v0.17.5
8 Mar 21:27:08 - [info] Node.js  version: v6.10.2
8 Mar 21:27:08 - [info] Linux 4.9.35-v7+ arm LE
8 Mar 21:27:10 - [info] Loading palette nodes

Gabriele

**Comment by vossilius** [comment]
Hi Gabriele,
Thanks for your quick response!

Here is mine:

> 8 Mar 22:10:55 - [info] Node-RED version: v0.18.4
> 8 Mar 22:10:55 - [info] Node.js  version: v4.8.4
> 8 Mar 22:10:55 - [info] Linux 3.10.102 x64 LE
> 8 Mar 22:10:55 - [info] Loading palette nodes

Yes, I am using `ws://blynk-cloud.com/websockets` and read the link you provided.

Trying the second link with my token does not return anything. 

I am using node-red-contrib-blynk-ws v0.3.0

I have installed wscat (https://github.com/websockets/wscat) on my server to test websocket from command line. It works. I can also successfully connect to `ws://blynk-cloud.com/websockets` with this tool. The client connects and then disconnects after a few seconds.

The flow I am using was working fine until I shut-down the server mid-January for some reason. Now, I reuse the same flow. Just moved the entire server to a new location. Only the router is different.

Best,
Thomas

**Comment by gablau** [comment]
Would you be able to apply this fix ["Fix error log"](https://github.com/gablau/node-red-contrib-blynk-ws/commit/d68b902cd8a8de5614c526aee8208c8fae43ad5d) to the library?
Apply the fix, restart node-red, try to reconnect and send me the log.

let me know
Gabriele

**Comment by gablau** [comment]
Handle CONNECT_REDIRECT in release [0.4.0](https://github.com/gablau/node-red-contrib-blynk-ws/releases/tag/0.4.0)

**Comment by vossilius** [comment]
Hi Gabriele,
...looking good! Got my pins connected. Thanks a lot!
Cheers,
Thomas
