### ISSUE TITLE
using the WRITE node with the zergba

### ISSUE THREAD

**Issue by scargill** [gablau/node-red-contrib-blynk-ws#7]
Help.. I'm reading from the WRITE EVENT node for zeRGBA and getting the colour value no problem into a global varuable, but cant figure out how to get that global var value back into the WRITE node.

So if NODE RE powers up it defaults the colour and at that point the zeRGBa has no idea what the current colour actually is, similarly if the colour is changed elsewhere... I need to get that colour back into the zeRGBa. I tried putting "255,0,0" into payload.. I even tried splitting it into 3 parts... cant get anything valid back into the WRITE node for that pin.

Help..

**Comment by scargill** [comment]
Specifically using a single pin zeRGBa, I want to push a colour value BACK to the zeRGBA but the docs refer merely to sending  a value in msg.payload into the write node... but for the zeRGBA I cant figure out the format.  data comes out of the zeRGBa as arrayOfValues[0] through 2... no problem but how to inject a value back....

**Comment by gablau** [comment]
Hi Peter,
You can use a "sync" or "sync all" node on node-red start to retrive the zergba value.
I never try to write on zergba :-) so i will need to try before at then I will let you know

**Comment by gablau** [comment]
For write on single pin try to pass an array with three value 
`msg.payload =[255, 0, 0];`

**Comment by scargill** [comment]
Doing exactly that didn’t bomb, but then what gets passed is not 255,0,0…. I tried sending a buffer [255,0,0] and the zeRGBa went to 0,0,73, then after manuly presetting the zeRGBA to all blue, next time I sent that 255,0,0 it went to 0, 45, 0

 

Pete

**Comment by scargill** [comment]
I tried [255,0,0] using both buffer and json types, neither bomb but neither result in the right colour going into the pin

**Comment by scargill** [comment]
Now I’ve tried sending payload from an inject node as both buffer and json to both write for that pin and sync for that pin [255,0,0] without effect

**Comment by gablau** [comment]
Hi Peter,
new version 0.6.0 of this library, added new zeRGBa node for handle zeRGBa widget in merge mode!
Let me know if it works properly.

Example flows for zeRGBa node:
```
[
    {
        "id": "d1642162.7d0bc",
        "type": "blynk-ws-zergba",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "pin": "0",
        "client": "e41126e7.38cd28",
        "x": 547,
        "y": 2357,
        "wires": [
            [
                "de8a0e23.737dd"
            ]
        ]
    },
    {
        "id": "609c8135.8c0d28",
        "type": "inject",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 127,
        "y": 2337,
        "wires": [
            [
                "a4a8acdf.b4fdb8"
            ]
        ]
    },
    {
        "id": "de8a0e23.737dd",
        "type": "debug",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "active": true,
        "console": false,
        "complete": "true",
        "x": 727,
        "y": 2357,
        "wires": []
    },
    {
        "id": "a4a8acdf.b4fdb8",
        "type": "function",
        "z": "ce0cd7ca.88c938",
        "name": "255+\"\\0\"+0+\"\\0\"+0",
        "func": "msg.payload = 0+\"\\0\"+255+\"\\0\"+0\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 307,
        "y": 2337,
        "wires": [
            [
                "d1642162.7d0bc"
            ]
        ]
    },
    {
        "id": "b46a153d.f8149",
        "type": "inject",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 127,
        "y": 2377,
        "wires": [
            [
                "41c8ce8e.523928"
            ]
        ]
    },
    {
        "id": "41c8ce8e.523928",
        "type": "function",
        "z": "ce0cd7ca.88c938",
        "name": "r255 g34 b22",
        "func": "msg.r = 255;\nmsg.g = 34;\nmsg.b = 22;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 297,
        "y": 2377,
        "wires": [
            [
                "d1642162.7d0bc"
            ]
        ]
    },
    {
        "id": "ed46b345.d3d11",
        "type": "inject",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 127,
        "y": 2297,
        "wires": [
            [
                "6291ecb1.9e9c24"
            ]
        ]
    },
    {
        "id": "6291ecb1.9e9c24",
        "type": "function",
        "z": "ce0cd7ca.88c938",
        "name": "#34DE01",
        "func": "msg.hex = \"#34DE01\";\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 277,
        "y": 2297,
        "wires": [
            [
                "d1642162.7d0bc"
            ]
        ]
    },
    {
        "id": "9bb5e9b1.a9d3e",
        "type": "inject",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "topic": "",
        "payload": "0;0;255",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 327,
        "y": 2417,
        "wires": [
            [
                "d1642162.7d0bc"
            ]
        ]
    },
    {
        "id": "9e8bd5e6.727db8",
        "type": "blynk-ws-out-sync",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "pin": "0",
        "pinmode": 0,
        "client": "e41126e7.38cd28",
        "x": 677,
        "y": 2277,
        "wires": []
    },
    {
        "id": "e9016dad.b731a",
        "type": "inject",
        "z": "ce0cd7ca.88c938",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 507,
        "y": 2277,
        "wires": [
            [
                "9e8bd5e6.727db8"
            ]
        ]
    },
    {
        "id": "e41126e7.38cd28",
        "type": "blynk-ws-client",
        "z": "",
        "name": "uno",
        "path": "wss://blynk-cloud.com/websockets",
        "key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "dbg_all": true,
        "dbg_read": false,
        "dbg_write": false,
        "dbg_notify": false,
        "dbg_mail": false,
        "dbg_prop": false,
        "dbg_sync": false,
        "dbg_bridge": false,
        "dbg_low": true,
        "dbg_pins": "",
        "multi_cmd": true,
        "proxy_type": "no",
        "proxy_url": ""
    }
]
```

**Comment by scargill** [comment]
Great. Travelling right now, back to UK tomorrow then I will check the node.

Pete

**Comment by scargill** [comment]
Fantastic, I'll use the simplest option 255;0;0

Marvellous work

**Comment by gablau** [comment]
Yes Peter,
I try and get the same strange error.
Need to open a post on blynk forum.
I don't think this is a problem of my library...

**Comment by gablau** [comment]
Post on blynk forum:
https://community.blynk.cc/t/strange-problem-with-zergba-widgets/25210

**Comment by scargill** [comment]
Oh dear, I was very excited as it all worked perfectly with one zeRGBa. The second one sets ok but if the app loses focus or you turn the phone off, when you go back in to the app, the second zeRGBa on the App comes up with the wrong colour.  At the end of Node-Red I have a Raspberry Pi and a control board driving the LED (Node-Red sees only MQTT which then talks to the board and that is all time-tested). At this point the LED still has the right colour but the APP is showing the wrong colour. Perhaps it would carry more weight if you contact Dmitriy at Blynk?

I will write in the Blynk forum

 

Pete
